### ISSUE TITLE
DOM mutation events are deprecated and a performance killer

### ISSUE THREAD

**Issue by rjgotten** [stevenmhunt/setidle#5]
Use a MutationObverser instead of DOM mutation events such as DOMNodeInserted. Mutation events were deprecated because their synchronous execution outright kills the browsers' rendering performance.

See also: https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mutation_events

**Comment by stevenmhunt** [comment]
I agree that this needs to be addressed. I am thinking that since the `DOMEventEmitter`class constructor currently wraps the `addEventListener` function, it could be extended to use `MutatationObverser` when the event is a DOM change event so that using the class is still simple but performance is increased. The point of the project is to help people with performance after all :smile:

**Comment by stevenmhunt** [comment]
Fixed in 8b3f2fcb689228d765455b40b94cfffbb1813fbf
